version: "3.7"

services:
  backend-nojapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: my-app
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: yarn dev
